import { The_Girl_Next_Door } from "@next/font/google";
import styles from "../../styles/product.module.css";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
const Product = () => {
  const [price, setPrice] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.productContainer}>
        <div className={styles.productLeft}>
          <div className={styles.productImgContainer}>
            <Image fill src="/img/pizza.png" object-fit="contain" />
          </div>
        </div>
        <div className={styles.productRight}>
          <h1 className={styles.productTitle}>PIZZATITLE</h1>
          <span className={styles.productPrice}>price</span>
          <p className={styles.productDesc}>Loukuqwd wd sqiwdqwdgugduwgdg v</p>
          <h3 className={styles.productChoose}>Choose </h3>
          <div className={styles.productSizes}>
            <div className={styles.productSize}>
              <Image src="/img/size.png" alt="" fill />
              <span className={styles.productNumber}>small</span>
            </div>

            <div className={styles.productSize}>
              <Image src="/img/size.png" alt="" fill />
              <span className={styles.productNumber}>medium</span>
            </div>

            <div className={styles.productSize}>
              <Image src="/img/size.png" alt="" fill />
              <span className={styles.productNumber}>large</span>
            </div>
          </div>
          <div className={styles.productAdd}>
            <input
              type="number"
              defaultValue={1}
              className={styles.productQuantity}
            />
            <button className={styles.productOrder}>Add to Cart</button>
          </div>
        </div>
      </div>
    </>
  );
};
export default Product;
