import styles from "../../styles/product.module.css";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
const Product = ({ product }) => {
  const [price, setPrice] = useState(0);
  const [quantity, setQuantity] = useState(1);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.productContainer}>
        <div className={styles.productLeft}>
          <div className={styles.productImgContainer}>
            <Image layout="fill" src={product.img} objectFit="contain" />
          </div>
        </div>
        <div className={styles.productRight}>
          <h1 className={styles.productTitle}>{product.title}</h1>
          <span className={styles.productPrice}>${product.price[price]}</span>
          <p className={styles.productDesc}>{product.description}</p>
          <h3 className={styles.productChoose}>
            Choose additional ingredients
          </h3>
          <div className={styles.productSizes}>
            <div
              className={styles.productSize}
              onClick={() => {
                setPrice(0);
              }}
            >
              <Image src="/img/size.png" alt="" layout="fill" />
              <span className={styles.productNumber}>small</span>
            </div>

            <div
              onClick={() => {
                setPrice(1);
              }}
              className={styles.productSize}
            >
              <Image src="/img/size.png" alt="" layout="fill" />
              <span className={styles.productNumber}>medium</span>
            </div>

            <div
              onClick={() => {
                setPrice(2);
              }}
              className={styles.productSize}
            >
              <Image src="/img/size.png" alt="" layout="fill" />
              <span className={styles.productNumber}>large</span>
            </div>
          </div>
          <div className={styles.productAdd}>
            <input
              type="number"
              onChange={(e) => {
                setQuantity(e.target.value);
              }}
              className={styles.productQuantity}
              defaultValue={1}
              min={1}
            />
            <button className={styles.productOrder}>Add to Cart</button>
          </div>
        </div>
      </div>
    </>
  );
};

export async function getServerSideProps({ params }) {
  const res = await axios.get(`http://localhost:3000/api/product/${params.id}`);
  console.log(res.data);
  return {
    props: {
      product: res.data.products,
    },
  };
}
export default Product;
