import Image from "next/image";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import styles from "../styles/cart.module.css";
import { useEffect, useState } from "react";
import {
  PayPalScriptProvider,
  PayPalButtons,
  usePayPalScriptReducer,
} from "@paypal/react-paypal-js";
const Cart = () => {
  const [open, setOpen] = useState(false);
  const amount = "2";
  const currency = "USD";
  const style = { layout: "vertical" };
  const dispatch = useDispatch();
  const { products, quantity, total } = useSelector((state) => state.cart);
  console.log(products);
  const ButtonWrapper = ({ currency, showSpinner }) => {
    // usePayPalScriptReducer can be use only inside children of PayPalScriptProviders
    // This is the main reason to wrap the PayPalButtons in a new component
    const [{ options, isPending }, dispatch] = usePayPalScriptReducer();

    useEffect(() => {
      dispatch({
        type: "resetOptions",
        value: {
          ...options,
          currency: currency,
        },
      });
    }, [currency, showSpinner]);

    return (
      <>
        {showSpinner && isPending && <div className="spinner" />}
        <PayPalButtons
          style={style}
          disabled={false}
          forceReRender={[amount, currency, style]}
          fundingSource={undefined}
          createOrder={(data, actions) => {
            return actions.order
              .create({
                purchase_units: [
                  {
                    amount: {
                      currency_code: currency,
                      value: amount,
                    },
                  },
                ],
              })
              .then((orderId) => {
                // Your code here after create the order
                return orderId;
              });
          }}
          onApprove={function (data, actions) {
            return actions.order.capture().then(function () {
              // Your code here after capture the order
            });
          }}
        />
      </>
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.cartContainer}>
        <div className={styles.cartLeft}>
          <div className={styles.cartTable}>
            <div className={styles.cartRow}>
              <div>Products</div>
              <div>Name</div>
              <div>Extras</div>
              <div>Price</div>
              <div>Quantity </div>
              <div>Total</div>
            </div>
            {products.map((prd, i) => (
              <div className={styles.cartProduct} key={i}>
                <div>
                  <div className={styles.cartImgContainer}>
                    <Image
                      src={prd.img}
                      alt=""
                      layout="fill"
                      objectFit="cover"
                    />
                  </div>
                </div>
                <div className={styles.cartName}>
                  <span>{prd.title}</span>
                </div>
                <div className={styles.cartExtra}>
                  <span>{prd.description}</span>
                </div>
                <div className={styles.cartPrice}>
                  <span>{prd.price}</span>
                </div>
                <div className={styles.cartQuantity}>
                  <span>{prd.quantity}</span>
                </div>
                <div className={styles.total}>
                  <span>${prd.price * prd.quantity}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className={styles.cartRight}>
          <div className={styles.cartRightWrapper}>
            <h2 className={styles.cartRightTitle}>CART TOTAL</h2>

            <div className={styles.cartTotalText}>
              <b className={styles.cartTotalTextTitle}>SubTotal:</b>${total}
            </div>

            <div className={styles.cartTotalText}>
              <b className={styles.cartTotalTextTitle}>Discount:</b>$0.00
            </div>

            <div className={styles.cartTotalText}>
              <b className={styles.cartTotalTextTitle}>Total:</b>${total}
            </div>
            {open ? (
              <div className={styles.cartPaypal}>
                <button className={styles.cartPaybutton}>
                  CASH ON DELIVERY
                </button>
                <PayPalScriptProvider
                  options={{
                    "client-id": "test",
                    components: "buttons",
                    currency: "USD",
                    "disable-funding": "credit,card,p24",
                  }}
                >
                  <ButtonWrapper currency={currency} showSpinner={false} />
                </PayPalScriptProvider>
              </div>
            ) : (
              <button
                onClick={() => {
                  setOpen(true);
                }}
                className={styles.cartButton}
              >
                CHECK OUT NOW
              </button>
            )}
          </div>
        </div>
      </div>
    </>
  );
};
export default Cart;
