import Head from "next/head";
import axios from "axios";
import Image from "next/image";

import ProductList from "./../component/ProductList";
import styles from "../styles/Home.module.css";
import Feature from "./../component/Feature";

export default function Home({ product }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Feature />
      <ProductList product={product} />
    </>
  );
}

export async function getServerSideProps(context) {
  const res = await axios.get("http://localhost:3000/api/product");

  return {
    props: {
      product: res.data,
    },
  };
}
