import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import { Inter } from "@next/font/google";
import ProductList from "./../component/ProductList";
import styles from "../styles/Home.module.css";
import Feature from "./../component/Feature";
const inter = Inter({ subsets: ["latin"] });

export async function getData() {
  const res = await axios.get("https://localhost:3000/product");
  if (!res) return res;
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Feature />
      <ProductList />
    </>
  );
}
